name: Build and Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - "404.html"

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
      - run: npm ci
      - run: npm run build

      - name: Commit build artifacts
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add dist/
          git commit -m "chore: build artifacts" || echo "No changes"
          git push
